# Generated by Django 5.1 on 2024-08-27 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('publication_date', models.DateField(default=datetime.date(1770, 1, 1))),
                ('genre', models.CharField(max_length=255)),
                ('description', models.TextField(default='No description available')),
                ('cover_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
