# Generated by Django 5.1 on 2024-08-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_year_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url_l',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_m',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_s',
            field=models.URLField(blank=True, null=True),
        ),
    ]
