# Generated by Django 5.1 on 2024-08-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_image_url_l_alter_book_image_url_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url_l',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_m',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_s',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
